### ISSUE TITLE
"ConsulAddress" does not support consul cluster

### ISSUE THREAD

**Issue by tangweichun** [openark/orchestrator#628] opened 2018-09-19 09:34 UTC
It seems "ConsulAddress" does not support consul cluster,I wonder how to avoid single-point failure when the first node "172.17.5.201" is down

"ConsulAddress": "172.17.5.201:8500,172.17.10.62:8500,172.17.11.242:8500"

error log:
[martini] Started GET /api/graceful-master-takeover/jigou/3307/ah-zabbix-ws/3307 for 172.17.1.51:60575
2018-09-19 17:26:25 ERROR Put http://172.17.5.201:8500,172.17.10.62:8500,172.17.11.242:8500/v1/kv/mysql/master/resource: invalid URL port "8500,172.17.10.62:8500,172.17.11.242:8500"
2018-09-19 17:26:25 ERROR Put http://172.17.5.201:8500,172.17.10.62:8500,172.17.11.242:8500/v1/kv/mysql/master/resource/hostname: invalid URL port "8500,172.17.10.62:8500,172.17.11.242:8500"
2018-09-19 17:26:25 ERROR Put http://172.17.5.201:8500,172.17.10.62:8500,172.17.11.242:8500/v1/kv/mysql/master/resource/port: invalid URL port "8500,172.17.10.62:8500,172.17.11.242:8500"
2018-09-19 17:26:25 ERROR Put http://172.17.5.201:8500,172.17.10.62:8500,172.17.11.242:8500/v1/kv/mysql/master/resource/ipv4: invalid URL port "8500,172.17.10.62:8500,172.17.11.242:8500"
2018-09-19 17:26:25 ERROR Put http://172.17.5.201:8500,172.17.10.62:8500,172.17.11.242:8500/v1/kv/mysql/master/resource/ipv6: invalid URL port "8500,172.17.10.62:8500,172.17.11.242:8500"

**Comment by utdrmac** [comment] 2019-01-18 15:33
Duplicate of #479 ?

**Comment by shlomi-noach** [comment] 2019-01-20 06:09
Duplicate indeed. Thank you for this feature request! I'm closing this issue in favor of #479

**Closed as completed by shlomi-noach** 2019-01-20 06:09 UTC
