### ISSUE TITLE
Placement of Orchestrator in the network topology

### ISSUE THREAD

**Issue by tapuhi** [openark/orchestrator#172] opened 2017-05-11 22:03 UTC
Hi , 

I would like to open a discussion about the placement of Orchestrator in the network topology. We, at WIX, are planing to  use Orchestrator which will update a consul template and ProxySql servers will grab/sync the new configurations when available ( Grosso modo :-) ) 

One of the scenarios Orchestrator can be an added value to ProxySql is that he can detect a Network Split and  Isolating one of DCs by  "telling"  proxySql  (when I say "tell" I mean after Orchestrator took care, if needed,  of failover/promoting/re-master etc....)  not to use that DC to serve IO.

 So where exactly the orchestrator must be placed in the Network? If we are using the same DCs/networks for the orchestrator nodes then both orchestrator APPS will be elected as ACTIVE during network split   and that will cause a mess in the ProxySql configuration because each Orchestrator will try to isolate the connections from the other side of the network/dc.

Some solutions offered:

-  Use a third DC for orchestrator. - What will happen if, for some reason that network gets Isolated?? probably no failover will occur

- Using a Galera  cluster for the Orchestrator backend database - Not sure which topology to use for this, please advice . 

We need to find a topology for orchestrator to allow him to do objective decisions on the mysql cluster topology.

**Comment by shlomi-noach** [comment] 2017-05-14 07:28
Good question and the very one I'm tackling right now. And with a lot of implications, too. And philosophical questions...

**Note** this discussion began in email, and I'm merging in this response some insights from out exchanged correspondence.

### Right now:
- The behavior is dictated by your MySQL backend setup.
- Orchestrator nodes all collaborate by communicating through the MySQL backend (not directly with each other).
- If you have a 2 datacenter master-master setup, with local orchestrator to each master then indeed a network partitioning will make both of them active. Bad.
- A friend of ours from Ghent University is using orchestrator on top of Galera cluster. He's running it on a single DC setup, so partitioning isn't handled (he's happy to run manual work on DC failure), but let's discuss:
  - Three nodes Galera setup
  - Each galera node also runs a local orchestrator, connecting to 127.0.0.1
  - As effect, an orchestrator node can only become leader if it has quorum
  - Which is very good.
  - For the low orchestrator backend workload, I *believe* (though haven't tried) you should be able to run cross-DC Galera setup, similarly.
  - you would then put three galera nodes, each in a different DC (use AWS as mediator if you don't have a third DC). Again each node will run local orchestrator connecting to 127.0.0.1

- @tapuhi you are running a 2-DC setup. You'd place one `orchestrator`+`galrea` node in each DC. You will then need a 3rd DC, let's make that an AWS setup. 
  - you need a 2-DC quorum. 
  - if only Amazon goes down, you don't have a problem. You have your two DC quorum.
  - if your DC1 goes black (network partitioned), then both DC2 and AWS agree that it is down and you have a quorum.
  - I think this would work well for you, assuming, again, Galera cross-DC latencies are acceptable.

### Plan for Q2 (things I'm working on right now, no guarantees etc.):

I'm writing a complete new deployment setup for orchestrator.
- orchestrator would be able to run on a `sqlite` backend (as opposed to `mysql`) -- already [POC](https://github.com/github/orchestrator/pull/63). But that's not the main point.
- orchestrator nodes would have *private*, local databases (be it sqlite or mysql)
- orchestrator nodes will collaborate via raft consensus.
- orchestrator node becomes leader if it has raft consensus.
- all nodes to discoveries and probing, but only active node runs failovers
- furthermore, before failover, active node will optionally consult with the other members: "is everyone agreeing we have a dead master?" -- if consensus is reached, failover is kicked.

You would then have one `orchestrator` node in each DC.
One thing to note about the `raft` implementation is that I don't see a way to force a specific node to grab leadership.
The issue is that you may be normally running from `DC1`, but the leader `orchestrator` node would happen to be running from `DC2` -- and this still works, but with latencies, implying longer recovery times. By all means not a deal breaker but something I'd like to tackle.

### Further notes

- you will likewise need a 3-DC Consul setup
  - or else, multiple DC-local setups, but then you need to update your multiple Consuls setups, and that's again raising distribution problems. What happens if you can't reach one?

### if a tree falls in the woods and no one is there to hear it, does it make a sound?

DC partitioning is so very complicated. What makes a recovery scenario?

- If the master is alive and well, but all of its replicas are partitioned away, should this be considered a failover scenario or not?
- If so, but replicas are also partitioned between themselves, should we really really kick the failover?
- if DCs are partitioned, and the DC where the master is has fewer replicas, should you choose to failover to the other DC based on the fact it has greater serving capacity?
- etc.
Not all questions will be answered to the satisfaction of everybody. I'm long enough in the orchestrator business to know different users expect *opposite* responses to same failure conditions.

**Comment by shlomi-noach** [comment] 2017-05-16 06:27
Related: https://github.com/github/orchestrator/issues/175

**Comment by shlomi-noach** [comment] 2018-04-20 10:50
Given that @tapuhi is running `orchestrator/raft` I'm closing this issue.

**Closed as completed by shlomi-noach** 2018-04-20 10:50 UTC
