### ISSUE TITLE
ERROR FlushNontrivialResolveCacheToDatabase() called, but HostnameResolveMethod is none

### ISSUE THREAD

**Issue by mia0x75** [openark/orchestrator#695] opened 2018-11-07 06:56 UTC
Orchestrator prints the error message once a minute, is that normal?

config:
```
  "HostnameResolveMethod": "none",
  "MySQLHostnameResolveMethod": "",
```
Thanks.

**Comment by shlomi-noach** [comment] 2018-11-13 08:59
Seems duplicate of https://github.com/github/orchestrator/issues/515, fixed by https://github.com/github/orchestrator/pull/547.

Which version are you using?

**Comment by shlomi-noach** [comment] 2018-11-13 09:04
solved by https://github.com/github/orchestrator/pull/712

**Comment by shlomi-noach** [comment] 2018-11-13 13:09
#712 is not merged yet. Reopening.

**Closed as completed** 2018-11-14 07:59 UTC
