### ISSUE TITLE
suppose to add option to let candidateReplica's sql thread to catch up io thread in GetCandidateReplica

### ISSUE THREAD

**Issue by MOON-CLJ** [openark/orchestrator#757] opened 2018-12-13 10:03 UTC
hi, RegroupReplicasGTID call GetCandidateReplica to choose a candidateReplica to promote。if there is some delay between candidateReplica's sql thread and io thread，we want to wait some time to let it catch up in our situation。what do you think about？

**Comment by shlomi-noach** [comment] 2018-12-13 10:44
It is interesting that you suggest this should take place in `GetCandidateReplica`.

I've had multiple similar requests to have the same wait, but just before finalizing master promotion. There is a contributor who is expected to submit a PR which does just that.

However, you suggest to take it to a lower level. I'm not sure. What is your objective?

**Comment by MOON-CLJ** [comment] 2018-12-13 10:54
@shlomi-noach "just before finalizing master promotion. " that's okay to us too。also what we want exactly。

**Comment by shlomi-noach** [comment] 2018-12-13 13:55
duplicate of https://github.com/github/orchestrator/issues/736

I'm closing this issue in favor of https://github.com/github/orchestrator/issues/736

**Closed as completed by shlomi-noach** 2018-12-13 13:55 UTC
