### ISSUE TITLE
3.0.2 fails to run on RHEL 6.7

### ISSUE THREAD

**Issue by deejaykim** [openark/orchestrator#297] opened 2017-09-13 21:14 UTC
Hi, I was happily running 2.1.5 on RHEL 6.7, but when I install the new 3.0.2 version using rpm I get the following error:

```
[root@d010108059224 orchestrator]# cat /etc/system-release
Red Hat Enterprise Linux Server release 6.7 (Santiago)

[root@d010108059224 orchestrator]# /usr/local/orchestrator/orchestrator --debug http &
[1] 1908
[root@d010108059224 orchestrator]# /usr/local/orchestrator/orchestrator: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/orchestrator/orchestrator)

[1]+  Exit 1                  /usr/local/orchestrator/orchestrator --debug http
```

Is this version meant to be run on RHEL 7?

**Comment by shlomi-noach** [comment] 2017-09-14 03:09
Can use please `uname -a`?

> Is this version meant to be run on RHEL 7?

it's a `golang` app, so it's meant to run anywhere ; I will try digging and find why it doesn't work (and could use the help). FWIW right now it's being compiled with `go1.7`. I'm planning to upgrade to `go1.9`. If an upgrade of `golang` is all it takes then that's the easy path.

**Comment by shlomi-noach** [comment] 2017-09-14 05:20
I'm meanwhile unable to find a reliable solution. I also don't have RHEL6 with me so I'm just checking theoretical solutions. If you are able to find something on your side that would be great.

An easy path for you is to build `orchestrator` on a ~~RHEL7~~ RHEL6.7 box:

```shell
git clone https://github.com/github/orchestrator.git
cd orchestrator
script/build
```
find result in `bin/` directory.

**Comment by deejaykim** [comment] 2017-09-14 17:47
Hi Shlomi thanks for looking into this. This is a AWS EC2 instance, BTW.

```
[root@d010108059224 ~]#  uname -a
Linux d010108059224.hidingmyhost.com 2.6.32-573.el6.x86_64 #1 SMP Wed Jul 1 18:23:37 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

[root@d010108059224 ~]#  rpm -qa | grep -i glib
glibc-2.12-1.166.el6.x86_64
dbus-glib-0.86-6.el6_4.x86_64
glibc-headers-2.12-1.166.el6.x86_64
glibc-devel-2.12-1.166.el6.x86_64
glibc-common-2.12-1.166.el6.x86_64
glib2-2.28.8-4.el6.x86_64
[root@d010108059224 ~]#
```

I'll see if I can grab hold of RHEL 7 and test it.

**Comment by shlomi-noach** [comment] 2017-09-15 04:46
Sorry I meant RHEL6.7, I confused the numbers

**Comment by shlomi-noach** [comment] 2017-09-15 05:34
For reference, I'm building the binaries on `Ubuntu precise (12.04.3 LTS)` using libc `2.15-0ubuntu10.13`

**Comment by silviabotros** [comment] 2017-09-15 16:22
Having the same issue.

```
bash-4.1$ uname -a
Linux hostname-redacted.sendgrid.net 2.6.32-504.el6.x86_64 #1 SMP Wed Oct 15 04:27:16 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/centos-release
CentOS release 6.6 (Final)
```

Since 3.0.2 was released this is what I get when I try to use orchestrator

```
/usr/local/orchestrator/orchestrator -c start-slave -i dbmainxxxxxx.sendgrid.net
/usr/local/orchestrator/orchestrator: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/orchestrator/orchestrator)

```

**Comment by shlomi-noach** [comment] 2017-09-17 19:55
Can you please test the following binaries for RHEL6 / CentOS6 ?

[orchestrator-3.0.2-rpms.zip](https://github.com/github/orchestrator/files/1309344/orchestrator-3.0.2-rpms.zip)

**Comment by hmcgonig** [comment] 2017-09-18 15:00
I hit this as well. I just had to build my own rpm on a centos 6 system and it works fine. It would be great if a centos6 rpm was hosted in the releases as well so that users wouldn't need to do this.

edit: just tested the binary that you posted @shlomi-noach, still seeing 
```
./orchestrator: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./orchestrator)
```

**Comment by silviabotros** [comment] 2017-09-18 17:00
@shlomi-noach still having the same issue with that attached rpm

```
# rpm -ihv orchestrator-3.0.2-1.x86_64.rpm
Preparing...                ########################################### [100%]
   1:orchestrator           ########################################### [100%]
# /usr/local/orchestrator/orchestrator -c start-slave -i testhost.sendgrid.net
/usr/local/orchestrator/orchestrator: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/orchestrator/orchestrator)
```

**Comment by shlomi-noach** [comment] 2017-09-18 18:41
Thank you for your feedback. Still trying to understand what changed. Now, the box where I build `3.0.2` happened to be deprovisioned, but used to run glibc `2.25`, and the attached binaries are built with glibc `2.19`.

**Comment by deejaykim** [comment] 2017-09-25 22:25
I'm not a system guru, but maybe try compiling it on a machine with glibc 2.12? It appears upgrading glibc is tricky and not generally recommended.

**Comment by sjmudd** [comment] 2017-09-26 05:34
For what it's worth I'm using my own rpms. I can't remember why now but know I started doing this a couple of years ago. It may have been because I have some rpm built-in internal automation that allowed me to build for CentOS 6 and 7 at the same time. I have certainly seen that some rpms built for go for CentOS 6 won't work on CentOS 7 (or the other way around I forget now) so if nothing else the rpms should ideally have a distribution suffix to indicate which OS they were built on. If of interest I can share the spec file I use here, though I'd still expect Shlomi's rpms to work fine, mine were just based on those that were built here.

**Comment by shlomi-noach** [comment] 2017-09-26 10:47
@deejaykim I'll give it a try.

**Comment by djuntgen** [comment] 2017-10-18 18:03
Ran into the same issue here after upgrading to 3.x

```
Linux 2.6.32-696.10.1.el6.x86_64 #1 SMP Tue Aug 22 18:51:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

[root@~]# cat /etc/redhat-release
CentOS release 6.9 (Final)
[root@dba ~]#


[root@~]# yum install orchestrator-cli.x86_64 orchestrator-client.x86_64
....
[root@~]# orchestrator
orchestrator: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by orchestrator)
[root@~]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.9 (Santiago)
```

FYI - as suggested, by @shlomi-noach - building on the machine itself fixed the issue.

**Comment by shlomi-noach** [comment] 2017-10-19 06:06
Gonna set myself a VM with CentOS6 ; however, this will have an effect on the entire build process.

**Comment by shlomi-noach** [comment] 2017-10-19 08:12
Please see these files for CentOS6 (will shortly add to releases page and to packagecloud):

[orchestrator-3.0.2-CentOS6-rpms.zip](https://github.com/github/orchestrator/files/1397583/orchestrator-3.0.2-CentOS6-rpms.zip)

**Comment by shlomi-noach** [comment] 2017-10-19 08:25
packagecloud packages are now updated at `el/6`. I removed `el/5` altogether.

**Comment by shlomi-noach** [comment] 2017-10-19 08:28
https://github.com/github/orchestrator/releases/tag/v3.0.2 now includes explicit packages for `RHEL6`

**Comment by shlomi-noach** [comment] 2017-10-19 08:29
If anyone can confirm these packages work, I can close this issue.

**Comment by djuntgen** [comment] 2017-10-19 12:27
@shlomi-noach - Confirmed, thank you!

**Comment by shlomi-noach** [comment] 2017-10-19 12:32
Thank you!

**Closed as completed by shlomi-noach** 2017-10-19 12:32 UTC

**Comment by igroene** [comment] 2018-12-26 15:44
Hi @shlomi-noach is rhel 6 not supported anymore? I see newer releases don't include the rhel6 rpm's anymore.

**Comment by shlomi-noach** [comment] 2018-12-26 16:05
I've been having issues recently building on RHEL6 and dropped this quietly. I see someone noticed... I can look into it again.
