### ISSUE TITLE
take-master makes co-master replicate from itself

### ISSUE THREAD

**Issue by Pomyk** [openark/orchestrator#573] opened 2018-08-09 10:32 UTC
I have 2 co-masters (and 1 slave). I dragged one of the masters onto the other in the web ui. take-master dialog appeared and I clicked ok. Now that master replicates from itself and the web ui shows all 3 machines lumped in the same spot.

versions: mariadb 10.3.8 with GTID, orchestrator compiled from current master (fadc7bc)

logs:
```
[martini] Started GET /api/take-master/devel-proxysql-01.gr/21318 for 10.0.0.248:56218
2018-08-09 11:56:02 DEBUG TakeMaster: will attempt making devel-proxysql-01.gr:21318 take its master devel-proxysql-01.gr:21317, now resolved as devel-proxysql-01.gr:21317
2018-08-09 11:56:02 INFO Stopped slave on devel-proxysql-01.gr:21317, Self:mysql-bin.000021:358, Exec:mysql-bin.000016:342
2018-08-09 11:56:02 INFO Stopped slave on devel-proxysql-01.gr:21318, Self:mysql-bin.000016:342, Exec:mysql-bin.000021:358
2018-08-09 11:56:02 INFO Will start slave on devel-proxysql-01.gr:21318 until coordinates: mysql-bin.000021:358
2018-08-09 11:56:02 INFO Stopped slave on devel-proxysql-01.gr:21318, Self:mysql-bin.000016:342, Exec:mysql-bin.000021:358
2018-08-09 11:56:02 DEBUG ChangeMasterTo: will attempt changing master on devel-proxysql-01.gr:21318 to devel-proxysql-01.gr:21318, mysql-bin.000016:342
2018-08-09 11:56:02 INFO ChangeMasterTo: Changed master on devel-proxysql-01.gr:21318 to: devel-proxysql-01.gr:21318, mysql-bin.000016:342. GTID: true
2018-08-09 11:56:02 DEBUG ChangeMasterTo: will attempt changing master on devel-proxysql-01.gr:21317 to devel-proxysql-01.gr:21318, mysql-bin.000016:342
2018-08-09 11:56:02 INFO ChangeMasterTo: Changed master on devel-proxysql-01.gr:21317 to: devel-proxysql-01.gr:21318, mysql-bin.000016:342. GTID: true
2018-08-09 11:56:02 INFO Started slave on devel-proxysql-01.gr:21318
2018-08-09 11:56:03 INFO Started slave on devel-proxysql-01.gr:21317
2018-08-09 11:56:03 INFO auditType:take-master instance:devel-proxysql-01.gr:21318 cluster:devel-proxysql-01.gr:21318 message:took master: devel-proxysql-01.gr:21317

**Comment by shlomi-noach** [comment] 2018-08-09 12:03
Can you please `orchestrator -c topology -alias <thecluster>`?

**Comment by shlomi-noach** [comment] 2018-08-09 12:04
It seems like you have multiple mysql servers running on the same box?
`Changed master on devel-proxysql-01.gr:21317 to: devel-proxysql-01.gr:21318`. Can you confirm that?

**Comment by Pomyk** [comment] 2018-08-09 12:47
Yes, all instances are on one machine.

Before take-master:
```
+ devel-proxysql-01.gr:21317   [0s,ok,10.3.8-MariaDB-log,ro,MIXED,>>,GTID,P-GTID]
+ devel-proxysql-01.gr:21318   [0s,ok,10.3.8-MariaDB-log,rw,MIXED,>>,P-GTID]
  + devel-proxysql-01.gr:21319 [0s,ok,10.3.8-MariaDB-log,ro,MIXED,>>,P-GTID]
```
After:
```
- devel-proxysql-01.gr:21318   [null,nonreplicating,10.3.8-MariaDB-log,rw,MIXED,>>,P-GTID]
  + devel-proxysql-01.gr:21317 [0s,lag,10.3.8-MariaDB-log,ro,MIXED,>>,GTID,P-GTID]
  + devel-proxysql-01.gr:21319 [0s,ok,10.3.8-MariaDB-log,ro,MIXED,>>,P-GTID]
```

**Comment by shlomi-noach** [comment] 2018-08-09 14:03
Can you please clarify which instance you promoted, and what became out of it? Which instance replicated from which? (I am assuming the output above is incorrect since you say a master replicates from itself as result).

**Comment by Pomyk** [comment] 2018-08-09 14:34
21317 and 21318 are co-masters
running `orchestrator-client -c all-clusters-masters` returns:
devel-proxysql-01.gr:21318

Dragging 21318 onto 21317 to take-master (which in this case makes no sense but is possible) results in 21318 replicating from itself (the other 2 instances also replicate from 21318).

**Comment by shlomi-noach** [comment] 2018-08-12 05:06
Thank you for clarifying.

**Comment by shlomi-noach** [comment] 2018-08-13 11:37
I am able to reproduce this. Interestingly, this only happens in one direction (to be more specific, the web interface only allows one of the masters to take the other).

**Comment by shlomi-noach** [comment] 2018-08-13 12:31
Addressed by https://github.com/github/orchestrator/pull/576

**Comment by shlomi-noach** [comment] 2018-08-15 05:28
@Pomyk any chance you can test https://github.com/github/orchestrator/pull/576 ?

**Comment by Pomyk** [comment] 2018-08-15 09:50
I will try to test it tomorrow.

**Comment by Pomyk** [comment] 2018-08-16 16:12
It works, thanks!

**Closed as completed** 2018-08-19 05:27 UTC
