### ISSUE TITLE
add a way to do orchestrator -c graceful-master-takeover via GUI

### ISSUE THREAD

**Issue by igroene** [openark/orchestrator#322] opened 2017-10-20 11:53 UTC
It would be nice to be have the possibility of doing a scheduled master switch from the GUI.
Drag and drop a slave on the master position to do a graceful failover (with a big red confirmation prompt) seems to be a good option.

**Comment by shlomi-noach** [comment] 2017-10-26 07:54
> Drag and drop a slave on the master position to do a graceful failover 

That's easy to implement, but makes for a UI inconsistency. Since typically when you drag a replica  R onto a server S, you mean to say you want R to replicate from S. Your suggestion that if S happens to be the master, and R happens to be a direct child, then this should translate as graceful takeover. 

I think it would be confusing UI-wise. Any thoughts on how to solve it?

**Comment by igroene** [comment] 2017-10-26 12:02
Yes that is a good point. I played with the UI a bit and the more intuitive way for me seems to be dragging the slave over to the little dot that is left of the master (the "root" of the tree)
The other option I can think of is adding an option in the config dialog of either the master (e.g. "Demote master") or the slave (e.g. "Promote as master").

**Comment by shlomi-noach** [comment] 2017-10-26 12:06
> the more intuitive way for me seems to be dragging the slave over to the little dot that is left of the master

unfortunately the jQuery draggable/droppable mechanism works by computing the position of the center of the object you drag. It would be near impossible to get to that small dot that is so far t othe left.

I was also thinking like a special, designated rubrik. None that sounds pretty. But who says we have to be pretty about it anyway.

**Comment by shlomi-noach** [comment] 2017-10-29 04:21
Solved as follows:

- if you drag onto the _right half_ of a box's `div`, operation is interpreted as a `relocate.`
- if you drag on the _left half_ of a box's `div`, _and where relevant_, operation is interpreted as `graceful-master-takeover` or as `take-master`.
- if you drag on the _left half_ of a box's `div`, _and where irrelevant_, operation is interpreted as `relocate`

<img width="1080" alt="screen shot 2017-10-27 at 18 55 48" src="https://user-images.githubusercontent.com/2607934/32140660-6af9e67a-bc71-11e7-89f1-97a10c8ea430.png">
<img width="1062" alt="screen shot 2017-10-27 at 18 55 39" src="https://user-images.githubusercontent.com/2607934/32140661-6b2b0f98-bc71-11e7-87f8-65e8678636ce.png">
<img width="855" alt="screen shot 2017-10-27 at 18 55 03" src="https://user-images.githubusercontent.com/2607934/32140662-6b4fa538-bc71-11e7-9186-46062d73ef19.png">
<img width="839" alt="screen shot 2017-10-27 at 18 54 58" src="https://user-images.githubusercontent.com/2607934/32140663-6b731018-bc71-11e7-9002-06cae9937362.png">

**Comment by shlomi-noach** [comment] 2017-10-31 05:56
closed by #329

**Comment by shlomi-noach** [comment] 2017-11-16 10:16
fixed and released in https://github.com/github/orchestrator/releases/tag/v3.0.3

**Comment by ManjotS** [comment] 2018-01-31 23:20
@shlomi-noach this does not seem to work in 3.0.6 with a single master and single slave as its impossible to drag to left side due to height restriction.

**Comment by shlomi-noach** [comment] 2018-02-01 06:10
@ManjotS Thank you. I'll look into it.

**Comment by shlomi-noach** [comment] 2018-02-02 11:30
@ManjotS doesn't reproduce for me:

<img width="845" alt="orchestrator-single-master-single-replica" src="https://user-images.githubusercontent.com/2607934/35731137-c9e5bd1e-0814-11e8-9aa8-b485be05964e.png">

Can you please open a new Issue and apply a couple screen snapshots? I'll be closing this Issue.

**Closed as completed by shlomi-noach** 2018-02-02 11:30 UTC
